CREATE TABLE app.admin
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id BIGINT                                  NOT NULL,
    username       VARCHAR(255)                            NOT NULL,
    nome_completo  VARCHAR(255)                            NOT NULL,
    password       VARCHAR(255)                            NOT NULL,
    email          VARCHAR(255)                            NOT NULL,
    ativo          BOOLEAN                                 NOT NULL,
    role           VARCHAR(255),
    dt_criacao     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT pk_admin PRIMARY KEY (id)
);

CREATE TABLE app.agendamento
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id   BIGINT                                  NOT NULL,
    cliente_id       BIGINT                                  NOT NULL,
    dt_agendamento   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    observacao       TEXT,
    status           VARCHAR(255)                            NOT NULL,
    dt_criacao       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    dt_atualizacao   TIMESTAMP WITHOUT TIME ZONE,
    dt_confirmacao   TIMESTAMP WITHOUT TIME ZONE,
    requer_sinal     BOOLEAN,
    percentual_sinal DECIMAL(5, 2),
    CONSTRAINT pk_agendamento PRIMARY KEY (id)
);

CREATE TABLE app.agendamento_funcionario
(
    agendamento_id BIGINT NOT NULL,
    funcionario_id BIGINT NOT NULL
);

CREATE TABLE app.agendamento_servico
(
    agendamento_id BIGINT NOT NULL,
    servico_id     BIGINT NOT NULL
);

CREATE TABLE app.bloqueio_agenda
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_id  BIGINT                                  NOT NULL,
    inicio_bloqueio TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    fim_bloqueio    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    descricao       VARCHAR(255),
    tipo_bloqueio   VARCHAR(255)                            NOT NULL,
    agendamento_id  BIGINT,
    CONSTRAINT pk_bloqueio_agenda PRIMARY KEY (id)
);

CREATE TABLE app.cargo_funcionario
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id BIGINT                                  NOT NULL,
    nome           VARCHAR(100)                            NOT NULL,
    descricao      VARCHAR(500),
    data_criacao   TIMESTAMP WITHOUT TIME ZONE,
    ativo          BOOLEAN,
    CONSTRAINT pk_cargo_funcionario PRIMARY KEY (id)
);

CREATE TABLE app.cartao_credito
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cliente_id      BIGINT,
    organizacao_id  BIGINT,
    nome_portador   VARCHAR(100)                            NOT NULL,
    numero_cartao   VARCHAR(19)                             NOT NULL,
    data_vencimento VARCHAR(7)                              NOT NULL,
    cvv             VARCHAR(4)                              NOT NULL,
    bandeira        VARCHAR(20)                             NOT NULL,
    is_principal    BOOLEAN                                 NOT NULL,
    ativo           BOOLEAN                                 NOT NULL,
    apelido         VARCHAR(50),
    CONSTRAINT pk_cartao_credito PRIMARY KEY (id)
);

CREATE TABLE app.categoria
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id BIGINT                                  NOT NULL,
    label          VARCHAR(255)                            NOT NULL,
    value          VARCHAR(255)                            NOT NULL,
    tipo           VARCHAR(50)                             NOT NULL,
    ativo          BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_categoria PRIMARY KEY (id)
);

CREATE TABLE app.cliente
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id         BIGINT                                  NOT NULL,
    username               VARCHAR(255)                            NOT NULL,
    nome_completo          VARCHAR(255)                            NOT NULL,
    password               VARCHAR(255)                            NOT NULL,
    email                  VARCHAR(255)                            NOT NULL,
    ativo                  BOOLEAN                                 NOT NULL,
    telefone               VARCHAR(15),
    data_nascimento        date,
    is_cadastro_incompleto BOOLEAN,
    cpf                    VARCHAR(14),
    role                   VARCHAR(255),
    dt_criacao             TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT pk_cliente PRIMARY KEY (id)
);

CREATE TABLE app.cobranca
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id               BIGINT                                  NOT NULL,
    cliente_id                   BIGINT                                  NOT NULL,
    agendamento_id               BIGINT,
    compra_id                    BIGINT,
    valor                        DECIMAL(10, 2)                          NOT NULL,
    valor_pago                   DECIMAL(10, 2),
    valor_pendente               DECIMAL(10, 2),
    status_cobranca              VARCHAR(50)                             NOT NULL,
    tipo_cobranca                VARCHAR(30)                             NOT NULL,
    subtipo_cobranca_agendamento VARCHAR(30),
    dt_vencimento                date,
    dt_criacao                   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    dt_atualizacao               TIMESTAMP WITHOUT TIME ZONE,
    dt_pagamento_completo        TIMESTAMP WITHOUT TIME ZONE,
    numero_cobranca              VARCHAR(20),
    observacoes                  TEXT,
    permite_parcelamento         BOOLEAN,
    juros_atraso                 DECIMAL(5, 2),
    multa_atraso                 DECIMAL(10, 2),
    percentual_sinal             DECIMAL(5, 2),
    cobranca_relacionada_id      BIGINT,
    gateway_payment_id           VARCHAR(100),
    gateway_payment_intent_id    VARCHAR(100),
    CONSTRAINT pk_cobranca PRIMARY KEY (id)
);

CREATE TABLE app.compra
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id BIGINT                                  NOT NULL,
    cliente_id     BIGINT                                  NOT NULL,
    valor_total    DECIMAL(10, 2)                          NOT NULL,
    valor_desconto DECIMAL(10, 2),
    valor_final    DECIMAL(10, 2)                          NOT NULL,
    status_compra  VARCHAR(50)                             NOT NULL,
    tipo_compra    VARCHAR(30)                             NOT NULL,
    observacoes    TEXT,
    numero_pedido  VARCHAR(20),
    dt_criacao     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    dt_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    dt_finalizacao TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_compra PRIMARY KEY (id)
);

CREATE TABLE app.compra_produto
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    compra_id      BIGINT                                  NOT NULL,
    produto_id     BIGINT                                  NOT NULL,
    quantidade     INTEGER                                 NOT NULL,
    preco_unitario DECIMAL(10, 2)                          NOT NULL,
    subtotal       DECIMAL(10, 2)                          NOT NULL,
    desconto_item  DECIMAL(10, 2),
    observacoes    TEXT,
    dt_adicionado  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT pk_compra_produto PRIMARY KEY (id)
);

CREATE TABLE app.config_sistema
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id            BIGINT                                  NOT NULL,
    usa_ecommerce             BOOLEAN                                 NOT NULL,
    usa_gestao_produtos       BOOLEAN                                 NOT NULL,
    usa_planos_para_clientes  BOOLEAN                                 NOT NULL,
    dispara_notificacoes_push BOOLEAN                                 NOT NULL,
    url_acesso                VARCHAR(255)                            NOT NULL,
    tenant_id                 VARCHAR(255)                            NOT NULL,
    dt_criacao                TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    dt_atualizacao            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_config_sistema PRIMARY KEY (id)
);

CREATE TABLE app.dados_faturamento_organizacao
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id     BIGINT                                  NOT NULL,
    cpf_cnpj           VARCHAR(18),
    agencia            VARCHAR(10),
    conta_numero       VARCHAR(20),
    conta_verificador  VARCHAR(2),
    numero_cartao      VARCHAR(19),
    dt_validade_cartao date,
    ativo              BOOLEAN                                 NOT NULL,
    dt_cadastro        TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    dt_atualizacao     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_dados_faturamento_organizacao PRIMARY KEY (id)
);

CREATE TABLE app.endereco
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cliente_id   BIGINT,
    logradouro   VARCHAR(255)                            NOT NULL,
    numero       VARCHAR(20)                             NOT NULL,
    bairro       VARCHAR(100)                            NOT NULL,
    cidade       VARCHAR(100)                            NOT NULL,
    cep          VARCHAR(10)                             NOT NULL,
    uf           VARCHAR(2)                              NOT NULL,
    referencia   TEXT,
    complemento  VARCHAR(255),
    is_principal BOOLEAN                                 NOT NULL,
    ativo        BOOLEAN                                 NOT NULL,
    tipo         VARCHAR(20),
    latitude     VARCHAR(255),
    longitude    VARCHAR(255),
    CONSTRAINT pk_endereco PRIMARY KEY (id)
);

CREATE TABLE app.funcionario
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id     BIGINT                                  NOT NULL,
    username           VARCHAR(255)                            NOT NULL,
    nome_completo      VARCHAR(255)                            NOT NULL,
    password           VARCHAR(255)                            NOT NULL,
    email              VARCHAR(255)                            NOT NULL,
    ativo              BOOLEAN                                 NOT NULL,
    foto_perfil        VARCHAR(255),
    cpf                VARCHAR(14),
    telefone           VARCHAR(20),
    data_nasc          date,
    data_contratacao   TIMESTAMP WITHOUT TIME ZONE,
    data_criacao       TIMESTAMP WITHOUT TIME ZONE,
    data_update        TIMESTAMP WITHOUT TIME ZONE,
    sexo               VARCHAR(20),
    nivel              INTEGER,
    apelido            VARCHAR(100),
    situacao           VARCHAR(50),
    cep                VARCHAR(10),
    logradouro         VARCHAR(255),
    numero             VARCHAR(20),
    complemento        VARCHAR(255),
    bairro             VARCHAR(100),
    cidade             VARCHAR(100),
    uf                 VARCHAR(2),
    rg                 VARCHAR(20),
    rg_org_emissor     VARCHAR(50),
    titulo_eleitor     VARCHAR(30),
    cert_militar       VARCHAR(30),
    cnh                VARCHAR(20),
    categ_habilitacao  VARCHAR(10),
    ctps               VARCHAR(30),
    ctps_serie         VARCHAR(20),
    pis_pasep          VARCHAR(30),
    naturalidade       VARCHAR(100),
    estado_civil       VARCHAR(50),
    grau_instrucao     VARCHAR(100),
    formacao           TEXT,
    salario            DECIMAL(10, 2),
    is_comissao        BOOLEAN,
    is_visivel_externo BOOLEAN,
    is_primeiro_acesso BOOLEAN,
    comissao           VARCHAR(50),
    nome_mae           VARCHAR(255),
    nome_pai           VARCHAR(255),
    banco              VARCHAR(100),
    agencia            VARCHAR(20),
    conta              VARCHAR(30),
    cargo_id           BIGINT,
    operacao           VARCHAR(20),
    jornada_semanal    VARCHAR(50),
    role               VARCHAR(255),
    CONSTRAINT pk_funcionario PRIMARY KEY (id)
);

CREATE TABLE app.funcionario_servico
(
    funcionario_id BIGINT NOT NULL,
    servico_id     BIGINT NOT NULL
);

CREATE TABLE app.horario_trabalho
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    jornada_dia_id BIGINT                                  NOT NULL,
    hora_inicio    time WITHOUT TIME ZONE                  NOT NULL,
    hora_fim       time WITHOUT TIME ZONE                  NOT NULL,
    CONSTRAINT pk_horario_trabalho PRIMARY KEY (id)
);

CREATE TABLE app.instance
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    instance_id    VARCHAR(100)                            NOT NULL,
    instance_name  VARCHAR(100)                            NOT NULL,
    integration    VARCHAR(255)                            NOT NULL,
    personality    VARCHAR(255),
    description    TEXT,
    organizacao_id BIGINT                                  NOT NULL,
    tool_id        BIGINT,
    webhook_id     BIGINT,
    CONSTRAINT pk_instance PRIMARY KEY (id)
);

CREATE TABLE app.instance_tools
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    get_services            BOOLEAN,
    get_professional        BOOLEAN,
    get_products            BOOLEAN,
    get_avaliable_schedules BOOLEAN,
    post_scheduling         BOOLEAN,
    send_text_message       BOOLEAN,
    send_media_message      BOOLEAN,
    post_confirmations      BOOLEAN,
    post_cancellations      BOOLEAN,
    CONSTRAINT pk_instance_tools PRIMARY KEY (id)
);

CREATE TABLE app.instance_webhook
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url       VARCHAR(255)                            NOT NULL,
    token     VARCHAR(255)                            NOT NULL,
    enabled   BOOLEAN                                 NOT NULL,
    by_events BOOLEAN,
    base64    BOOLEAN,
    events    TEXT,
    CONSTRAINT pk_instance_webhook PRIMARY KEY (id)
);

CREATE TABLE app.jornada_dia
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_id BIGINT                                  NOT NULL,
    dia_semana     VARCHAR(255)                            NOT NULL,
    ativo          BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_jornada_dia PRIMARY KEY (id)
);

CREATE TABLE app.jornada_trabalho
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_id BIGINT                                  NOT NULL,
    dia_semana     VARCHAR(255)                            NOT NULL,
    hora_inicio    time WITHOUT TIME ZONE                  NOT NULL,
    hora_fim       time WITHOUT TIME ZONE                  NOT NULL,
    ativo          BOOLEAN,
    CONSTRAINT pk_jornada_trabalho PRIMARY KEY (id)
);

CREATE TABLE app.organizacao
(
    id                                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cnpj                               VARCHAR(18)                             NOT NULL,
    razao_social                       VARCHAR(255),
    nome_fantasia                      VARCHAR(255),
    publico_alvo                       VARCHAR(255),
    inscricao_estadual                 VARCHAR(50),
    email_principal                    VARCHAR(255),
    telefone1                          VARCHAR(20),
    telefone2                          VARCHAR(20),
    whatsapp                           VARCHAR(20),
    endereco_principal_id              BIGINT,
    plano_id                           BIGINT                                  NOT NULL,
    slug                               VARCHAR(255)                            NOT NULL,
    config_sistema_id                  BIGINT,
    limites_personalizados_id          BIGINT,
    ativo                              BOOLEAN                                 NOT NULL,
    dt_cadastro                        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    dt_atualizacao                     TIMESTAMP WITHOUT TIME ZONE,
    responsavel_nome                   VARCHAR(255),
    responsavel_email                  VARCHAR(255),
    responsavel_telefone               VARCHAR(255),
    tema_nome                          VARCHAR(100),
    tema_tipo                          VARCHAR(50),
    tema_cor_primary                   VARCHAR(255),
    tema_cor_secondary                 VARCHAR(255),
    tema_cor_accent                    VARCHAR(255),
    tema_cor_background                VARCHAR(255),
    tema_cor_text                      VARCHAR(255),
    tema_cor_text_secondary            VARCHAR(255),
    tema_cor_card_background           VARCHAR(255),
    tema_cor_card_background_secondary VARCHAR(255),
    tema_cor_button_text               VARCHAR(255),
    tema_cor_background_linear         VARCHAR(255),
    tema_cor_success                   VARCHAR(255),
    tema_cor_warning                   VARCHAR(255),
    tema_cor_error                     VARCHAR(255),
    tema_cor_info                      VARCHAR(255),
    tema_cor_border                    VARCHAR(255),
    tema_cor_border_light              VARCHAR(255),
    tema_cor_divider                   VARCHAR(255),
    tema_cor_overlay                   VARCHAR(255),
    tema_cor_modal_background          VARCHAR(255),
    tema_cor_input_background          VARCHAR(255),
    tema_cor_input_border              VARCHAR(255),
    tema_cor_input_focus               VARCHAR(255),
    tema_cor_placeholder               VARCHAR(255),
    tema_cor_nav_background            VARCHAR(255),
    tema_cor_nav_hover                 VARCHAR(255),
    tema_cor_nav_active                VARCHAR(255),
    tema_cor_online                    VARCHAR(255),
    tema_cor_offline                   VARCHAR(255),
    tema_cor_away                      VARCHAR(255),
    tema_cor_busy                      VARCHAR(255),
    tema_font_heading                  VARCHAR(255),
    tema_font_body                     VARCHAR(255),
    tema_font_mono                     VARCHAR(255),
    tema_border_radius_small           VARCHAR(255),
    tema_border_radius_medium          VARCHAR(255),
    tema_border_radius_large           VARCHAR(255),
    tema_border_radius_xl              VARCHAR(255),
    tema_border_radius_full            VARCHAR(255),
    tema_shadow_base                   VARCHAR(255),
    tema_shadow_md                     VARCHAR(255),
    tema_shadow_lg                     VARCHAR(255),
    tema_shadow_primary_glow           VARCHAR(255),
    tema_shadow_accent_glow            VARCHAR(255),
    redes_sociais_instagram            VARCHAR(255),
    redes_sociais_facebook             VARCHAR(255),
    redes_sociais_whatsapp             VARCHAR(255),
    redes_sociais_linkedin             VARCHAR(255),
    redes_sociais_messenger            VARCHAR(255),
    redes_sociais_site                 VARCHAR(255),
    redes_sociais_youtube              VARCHAR(255),
    CONSTRAINT pk_organizacao PRIMARY KEY (id)
);

CREATE TABLE app.pagamento
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cobranca_id       BIGINT                                  NOT NULL,
    cliente_id        BIGINT                                  NOT NULL,
    organizacao_id    BIGINT                                  NOT NULL,
    cartao_credito_id BIGINT,
    valor             DECIMAL(10, 2)                          NOT NULL,
    dt_pagamento      TIMESTAMP WITHOUT TIME ZONE,
    forma_pagamento   VARCHAR(50),
    metodo_pagamento  VARCHAR(50),
    status_pagamento  VARCHAR(20)                             NOT NULL,
    numero_transacao  VARCHAR(50),
    transacao_id      VARCHAR(255),
    comprovante_url   VARCHAR(500),
    observacoes       TEXT,
    dt_criacao        TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    dt_atualizacao    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_pagamento PRIMARY KEY (id)
);

CREATE TABLE app.page
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id        BIGINT                                  NOT NULL,
    slug             VARCHAR(100)                            NOT NULL,
    title            VARCHAR(255)                            NOT NULL,
    description      TEXT,
    active           BOOLEAN                                 NOT NULL,
    meta_title       VARCHAR(255),
    meta_description TEXT,
    meta_keywords    TEXT,
    dt_criacao       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    dt_atualizacao   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_page PRIMARY KEY (id)
);

CREATE TABLE app.page_component
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    page_id        BIGINT                                  NOT NULL,
    type           VARCHAR(50)                             NOT NULL,
    order_index    INTEGER                                 NOT NULL,
    active         BOOLEAN                                 NOT NULL,
    props_json     TEXT,
    style_config   TEXT,
    dt_criacao     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    dt_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_page_component PRIMARY KEY (id)
);

CREATE TABLE app.plano
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome                 VARCHAR(100)                            NOT NULL,
    descricao            TEXT,
    recorrencia          VARCHAR(50)                             NOT NULL,
    valor_unitario       DECIMAL(10, 2)                          NOT NULL,
    dt_criacao           TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    dt_atualizacao       TIMESTAMP WITHOUT TIME ZONE,
    dia_cobranca         TIMESTAMP WITHOUT TIME ZONE,
    data_ultima_cobranca TIMESTAMP WITHOUT TIME ZONE,
    ativo                BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_plano PRIMARY KEY (id)
);

CREATE TABLE app.plano_cliente
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cliente_id       BIGINT                                  NOT NULL,
    plano_servico_id BIGINT                                  NOT NULL,
    cobranca_id      BIGINT,
    dt_inicio        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    dt_fim           TIMESTAMP WITHOUT TIME ZONE,
    status           VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_plano_cliente PRIMARY KEY (id)
);

CREATE TABLE app.plano_limites
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    limite_cliente       INTEGER,
    limite_agendamento   INTEGER,
    limite_colaborador   INTEGER,
    permite_landing_page BOOLEAN,
    plano_id             BIGINT                                  NOT NULL,
    CONSTRAINT pk_plano_limites PRIMARY KEY (id)
);

CREATE TABLE app.plano_servico
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id BIGINT                                  NOT NULL,
    nome           VARCHAR(100)                            NOT NULL,
    descricao      TEXT,
    preco          DECIMAL(10, 2)                          NOT NULL,
    validade_dias  INTEGER,
    dt_criacao     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    dt_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    ativo          BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_plano_servico PRIMARY KEY (id)
);

CREATE TABLE app.produto
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id      BIGINT                                  NOT NULL,
    nome                VARCHAR(255)                            NOT NULL,
    categoria_id        BIGINT                                  NOT NULL,
    genero              VARCHAR(100),
    avaliacao           DECIMAL(3, 2),
    total_avaliacoes    INTEGER,
    desconto_percentual INTEGER,
    destaque            BOOLEAN                                 NOT NULL,
    ativo               BOOLEAN                                 NOT NULL,
    descricao           TEXT,
    codigo_barras       VARCHAR(50),
    codigo_interno      VARCHAR(50),
    preco               DECIMAL(10, 2)                          NOT NULL,
    preco_custo         DECIMAL(10, 2),
    quantidade_estoque  INTEGER,
    estoque_minimo      INTEGER,
    unidade             VARCHAR(10),
    status_produto      VARCHAR(255)                            NOT NULL,
    marca               VARCHAR(100),
    modelo              VARCHAR(50),
    peso_kg             DECIMAL(8, 3),
    dt_criacao          TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    dt_atualizacao      TIMESTAMP WITHOUT TIME ZONE,
    usuario_criacao     VARCHAR(100),
    usuario_atualizacao VARCHAR(100),
    CONSTRAINT pk_produto PRIMARY KEY (id)
);

CREATE TABLE app.produto_como_usar
(
    produto_id  BIGINT  NOT NULL,
    passo       TEXT    NOT NULL,
    passo_ordem INTEGER NOT NULL,
    CONSTRAINT pk_produto_como_usar PRIMARY KEY (produto_id, passo_ordem)
);

CREATE TABLE app.produto_especificacoes
(
    produto_id BIGINT       NOT NULL,
    valor      TEXT,
    chave      VARCHAR(100) NOT NULL,
    CONSTRAINT pk_produto_especificacoes PRIMARY KEY (produto_id, chave)
);

CREATE TABLE app.produto_imagens
(
    produto_id BIGINT        NOT NULL,
    url_imagem VARCHAR(1000) NOT NULL
);

CREATE TABLE app.produto_ingredientes
(
    produto_id  BIGINT NOT NULL,
    ingrediente TEXT   NOT NULL
);

CREATE TABLE app.produto_relacionados_assoc
(
    produto_id     BIGINT NOT NULL,
    relacionado_id BIGINT NOT NULL,
    CONSTRAINT pk_produto_relacionados_assoc PRIMARY KEY (produto_id, relacionado_id)
);

CREATE TABLE app.produto_utilizados_assoc
(
    produto_id   BIGINT NOT NULL,
    utilizado_id BIGINT NOT NULL,
    CONSTRAINT pk_produto_utilizados_assoc PRIMARY KEY (produto_id, utilizado_id)
);

CREATE TABLE app.servico
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id         BIGINT                                  NOT NULL,
    nome                   VARCHAR(255)                            NOT NULL,
    categoria_id           BIGINT                                  NOT NULL,
    genero                 VARCHAR(255)                            NOT NULL,
    descricao              TEXT,
    tempo_estimado_minutos INTEGER                                 NOT NULL,
    preco                  DECIMAL(10, 2)                          NOT NULL,
    desconto               INTEGER,
    dt_criacao             TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    dt_atualizacao         TIMESTAMP WITHOUT TIME ZONE,
    ativo                  BOOLEAN                                 NOT NULL,
    is_home                BOOLEAN,
    is_avaliacao           BOOLEAN                                 NOT NULL,
    usuario_atualizacao    VARCHAR(255),
    CONSTRAINT pk_servico PRIMARY KEY (id)
);

CREATE TABLE app.servico_imagens
(
    servico_id BIGINT        NOT NULL,
    url_imagem VARCHAR(1000) NOT NULL
);

CREATE TABLE app.servico_produtos
(
    servico_id   BIGINT       NOT NULL,
    produto_nome VARCHAR(255) NOT NULL
);

CREATE TABLE app.tb_roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tb_roles PRIMARY KEY (id)
);

CREATE TABLE app.tenant
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    subdomain      VARCHAR(100)                            NOT NULL,
    theme          VARCHAR(50),
    active         BOOLEAN                                 NOT NULL,
    email          VARCHAR(255),
    description    TEXT,
    theme_config   TEXT,
    dt_criacao     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    dt_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tenant PRIMARY KEY (id)
);

CREATE TABLE admin.plano_bellory
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo                    VARCHAR(50)                             NOT NULL,
    nome                      VARCHAR(100)                            NOT NULL,
    tagline                   VARCHAR(255),
    descricao_completa        TEXT,
    ativo                     BOOLEAN                                 NOT NULL,
    popular                   BOOLEAN                                 NOT NULL,
    cta                       VARCHAR(200),
    badge                     VARCHAR(100),
    icone                     VARCHAR(50),
    cor                       VARCHAR(7),
    gradiente                 VARCHAR(100),
    preco_mensal              DECIMAL(10, 2)                          NOT NULL,
    preco_anual               DECIMAL(10, 2)                          NOT NULL,
    desconto_percentual_anual DOUBLE PRECISION,
    features                  JSONB,
    cartao_credito_id         BIGINT,
    dt_criacao                TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    dt_atualizacao            TIMESTAMP WITHOUT TIME ZONE,
    user_criacao              BIGINT,
    user_atualizacao          BIGINT,
    ordem_exibicao            INTEGER,
    CONSTRAINT pk_plano_bellory PRIMARY KEY (id)
);

CREATE TABLE admin.plano_limites_bellory
(
    id                               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    plano_bellory_id                 BIGINT                                  NOT NULL,
    max_agendamentos_mes             INTEGER,
    max_usuarios                     INTEGER,
    max_clientes                     INTEGER,
    max_servicos                     INTEGER,
    max_unidades                     INTEGER,
    permite_agendamento_online       BOOLEAN,
    permite_whatsapp                 BOOLEAN,
    permite_site                     BOOLEAN,
    permite_ecommerce                BOOLEAN,
    permite_relatorios_avancados     BOOLEAN,
    permite_api                      BOOLEAN,
    permite_integracao_personalizada BOOLEAN,
    suporte_prioritario              BOOLEAN,
    suporte_24x7                     BOOLEAN,
    CONSTRAINT pk_plano_limites_bellory PRIMARY KEY (id)
);

ALTER TABLE admin.plano_bellory
    ADD CONSTRAINT uc_plano_bellory_codigo UNIQUE (codigo);

ALTER TABLE admin.plano_limites_bellory
    ADD CONSTRAINT uc_plano_limites_bellory_plano_bellory UNIQUE (plano_bellory_id);

ALTER TABLE admin.plano_bellory
    ADD CONSTRAINT FK_PLANO_BELLORY_ON_CARTAOCREDITO FOREIGN KEY (cartao_credito_id) REFERENCES app.cartao_credito (id);

ALTER TABLE admin.plano_limites_bellory
    ADD CONSTRAINT FK_PLANO_LIMITES_BELLORY_ON_PLANO_BELLORY FOREIGN KEY (plano_bellory_id) REFERENCES admin.plano_bellory (id);

ALTER TABLE app.admin
    ADD CONSTRAINT uc_admin_email UNIQUE (email);

ALTER TABLE app.admin
    ADD CONSTRAINT uc_admin_username UNIQUE (username);

ALTER TABLE app.bloqueio_agenda
    ADD CONSTRAINT uc_bloqueio_agenda_agendamento UNIQUE (agendamento_id);

ALTER TABLE app.cliente
    ADD CONSTRAINT uc_cliente_email UNIQUE (email);

ALTER TABLE app.cliente
    ADD CONSTRAINT uc_cliente_username UNIQUE (username);

ALTER TABLE app.cobranca
    ADD CONSTRAINT uc_cobranca_agendamento UNIQUE (agendamento_id);

ALTER TABLE app.cobranca
    ADD CONSTRAINT uc_cobranca_cobranca_relacionada UNIQUE (cobranca_relacionada_id);

ALTER TABLE app.cobranca
    ADD CONSTRAINT uc_cobranca_compra UNIQUE (compra_id);

ALTER TABLE app.cobranca
    ADD CONSTRAINT uc_cobranca_numero_cobranca UNIQUE (numero_cobranca);

ALTER TABLE app.compra
    ADD CONSTRAINT uc_compra_numero_pedido UNIQUE (numero_pedido);

ALTER TABLE app.config_sistema
    ADD CONSTRAINT uc_config_sistema_organizacao UNIQUE (organizacao_id);

ALTER TABLE app.dados_faturamento_organizacao
    ADD CONSTRAINT uc_dados_faturamento_organizacao_organizacao UNIQUE (organizacao_id);

ALTER TABLE app.funcionario
    ADD CONSTRAINT uc_funcionario_email UNIQUE (email);

ALTER TABLE app.funcionario
    ADD CONSTRAINT uc_funcionario_username UNIQUE (username);

ALTER TABLE app.instance
    ADD CONSTRAINT uc_instance_instanceid UNIQUE (instance_id);

ALTER TABLE app.instance
    ADD CONSTRAINT uc_instance_instancename UNIQUE (instance_name);

ALTER TABLE app.instance
    ADD CONSTRAINT uc_instance_tool UNIQUE (tool_id);

ALTER TABLE app.instance
    ADD CONSTRAINT uc_instance_webhook UNIQUE (webhook_id);

ALTER TABLE app.organizacao
    ADD CONSTRAINT uc_organizacao_cnpj UNIQUE (cnpj);

ALTER TABLE app.organizacao
    ADD CONSTRAINT uc_organizacao_config_sistema UNIQUE (config_sistema_id);

ALTER TABLE app.organizacao
    ADD CONSTRAINT uc_organizacao_endereco_principal UNIQUE (endereco_principal_id);

ALTER TABLE app.organizacao
    ADD CONSTRAINT uc_organizacao_limites_personalizados UNIQUE (limites_personalizados_id);

ALTER TABLE app.organizacao
    ADD CONSTRAINT uc_organizacao_slug UNIQUE (slug);

ALTER TABLE app.pagamento
    ADD CONSTRAINT uc_pagamento_numero_transacao UNIQUE (numero_transacao);

ALTER TABLE app.plano_cliente
    ADD CONSTRAINT uc_plano_cliente_cobranca UNIQUE (cobranca_id);

ALTER TABLE app.plano_limites
    ADD CONSTRAINT uc_plano_limites_plano UNIQUE (plano_id);

ALTER TABLE app.plano
    ADD CONSTRAINT uc_plano_nome UNIQUE (nome);

ALTER TABLE app.produto
    ADD CONSTRAINT uc_produto_codigo_interno UNIQUE (codigo_interno);

ALTER TABLE app.tb_roles
    ADD CONSTRAINT uc_tb_roles_nome UNIQUE (nome);

ALTER TABLE app.tenant
    ADD CONSTRAINT uc_tenant_subdomain UNIQUE (subdomain);

CREATE INDEX idx_component_page_order ON app.page_component (page_id, order_index);

CREATE UNIQUE INDEX idx_page_tenant_slug ON app.page (tenant_id, slug);

CREATE UNIQUE INDEX idx_tenant_subdomain ON app.tenant (subdomain);

ALTER TABLE app.admin
    ADD CONSTRAINT FK_ADMIN_ON_ORGANIZACAO FOREIGN KEY (organizacao_id) REFERENCES app.organizacao (id);

ALTER TABLE app.agendamento
    ADD CONSTRAINT FK_AGENDAMENTO_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES app.cliente (id);

ALTER TABLE app.agendamento
    ADD CONSTRAINT FK_AGENDAMENTO_ON_ORGANIZACAO FOREIGN KEY (organizacao_id) REFERENCES app.organizacao (id);

ALTER TABLE app.bloqueio_agenda
    ADD CONSTRAINT FK_BLOQUEIO_AGENDA_ON_AGENDAMENTO FOREIGN KEY (agendamento_id) REFERENCES app.agendamento (id);

ALTER TABLE app.bloqueio_agenda
    ADD CONSTRAINT FK_BLOQUEIO_AGENDA_ON_FUNCIONARIO FOREIGN KEY (funcionario_id) REFERENCES app.funcionario (id);

ALTER TABLE app.cargo_funcionario
    ADD CONSTRAINT FK_CARGO_FUNCIONARIO_ON_ORGANIZACAO FOREIGN KEY (organizacao_id) REFERENCES app.organizacao (id);

ALTER TABLE app.cartao_credito
    ADD CONSTRAINT FK_CARTAO_CREDITO_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES app.cliente (id);

ALTER TABLE app.cartao_credito
    ADD CONSTRAINT FK_CARTAO_CREDITO_ON_ORGANIZACAO FOREIGN KEY (organizacao_id) REFERENCES app.organizacao (id);

ALTER TABLE app.categoria
    ADD CONSTRAINT FK_CATEGORIA_ON_ORGANIZACAO FOREIGN KEY (organizacao_id) REFERENCES app.organizacao (id);

ALTER TABLE app.cliente
    ADD CONSTRAINT FK_CLIENTE_ON_ORGANIZACAO FOREIGN KEY (organizacao_id) REFERENCES app.organizacao (id);

ALTER TABLE app.cobranca
    ADD CONSTRAINT FK_COBRANCA_ON_AGENDAMENTO FOREIGN KEY (agendamento_id) REFERENCES app.agendamento (id);

ALTER TABLE app.cobranca
    ADD CONSTRAINT FK_COBRANCA_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES app.cliente (id);

ALTER TABLE app.cobranca
    ADD CONSTRAINT FK_COBRANCA_ON_COBRANCA_RELACIONADA FOREIGN KEY (cobranca_relacionada_id) REFERENCES app.cobranca (id);

ALTER TABLE app.cobranca
    ADD CONSTRAINT FK_COBRANCA_ON_COMPRA FOREIGN KEY (compra_id) REFERENCES app.compra (id);

ALTER TABLE app.cobranca
    ADD CONSTRAINT FK_COBRANCA_ON_ORGANIZACAO FOREIGN KEY (organizacao_id) REFERENCES app.organizacao (id);

ALTER TABLE app.compra
    ADD CONSTRAINT FK_COMPRA_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES app.cliente (id);

ALTER TABLE app.compra
    ADD CONSTRAINT FK_COMPRA_ON_ORGANIZACAO FOREIGN KEY (organizacao_id) REFERENCES app.organizacao (id);

ALTER TABLE app.compra_produto
    ADD CONSTRAINT FK_COMPRA_PRODUTO_ON_COMPRA FOREIGN KEY (compra_id) REFERENCES app.compra (id);

ALTER TABLE app.compra_produto
    ADD CONSTRAINT FK_COMPRA_PRODUTO_ON_PRODUTO FOREIGN KEY (produto_id) REFERENCES app.produto (id);

ALTER TABLE app.config_sistema
    ADD CONSTRAINT FK_CONFIG_SISTEMA_ON_ORGANIZACAO FOREIGN KEY (organizacao_id) REFERENCES app.organizacao (id);

ALTER TABLE app.dados_faturamento_organizacao
    ADD CONSTRAINT FK_DADOS_FATURAMENTO_ORGANIZACAO_ON_ORGANIZACAO FOREIGN KEY (organizacao_id) REFERENCES app.organizacao (id);

ALTER TABLE app.endereco
    ADD CONSTRAINT FK_ENDERECO_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES app.cliente (id);

ALTER TABLE app.funcionario
    ADD CONSTRAINT FK_FUNCIONARIO_ON_CARGO FOREIGN KEY (cargo_id) REFERENCES app.cargo_funcionario (id);

ALTER TABLE app.funcionario
    ADD CONSTRAINT FK_FUNCIONARIO_ON_ORGANIZACAO FOREIGN KEY (organizacao_id) REFERENCES app.organizacao (id);

ALTER TABLE app.horario_trabalho
    ADD CONSTRAINT FK_HORARIO_TRABALHO_ON_JORNADA_DIA FOREIGN KEY (jornada_dia_id) REFERENCES app.jornada_dia (id);

ALTER TABLE app.instance
    ADD CONSTRAINT FK_INSTANCE_ON_ORGANIZACAO FOREIGN KEY (organizacao_id) REFERENCES app.organizacao (id);

ALTER TABLE app.instance
    ADD CONSTRAINT FK_INSTANCE_ON_TOOL FOREIGN KEY (tool_id) REFERENCES app.instance_tools (id);

ALTER TABLE app.instance
    ADD CONSTRAINT FK_INSTANCE_ON_WEBHOOK FOREIGN KEY (webhook_id) REFERENCES app.instance_webhook (id);

ALTER TABLE app.jornada_dia
    ADD CONSTRAINT FK_JORNADA_DIA_ON_FUNCIONARIO FOREIGN KEY (funcionario_id) REFERENCES app.funcionario (id);

ALTER TABLE app.jornada_trabalho
    ADD CONSTRAINT FK_JORNADA_TRABALHO_ON_FUNCIONARIO FOREIGN KEY (funcionario_id) REFERENCES app.funcionario (id);

ALTER TABLE app.organizacao
    ADD CONSTRAINT FK_ORGANIZACAO_ON_CONFIG_SISTEMA FOREIGN KEY (config_sistema_id) REFERENCES app.config_sistema (id);

ALTER TABLE app.organizacao
    ADD CONSTRAINT FK_ORGANIZACAO_ON_ENDERECO_PRINCIPAL FOREIGN KEY (endereco_principal_id) REFERENCES app.endereco (id);

ALTER TABLE app.organizacao
    ADD CONSTRAINT FK_ORGANIZACAO_ON_LIMITES_PERSONALIZADOS FOREIGN KEY (limites_personalizados_id) REFERENCES admin.plano_limites_bellory (id);

ALTER TABLE app.organizacao
    ADD CONSTRAINT FK_ORGANIZACAO_ON_PLANO FOREIGN KEY (plano_id) REFERENCES admin.plano_bellory (id);

ALTER TABLE app.pagamento
    ADD CONSTRAINT FK_PAGAMENTO_ON_CARTAO_CREDITO FOREIGN KEY (cartao_credito_id) REFERENCES app.cartao_credito (id);

ALTER TABLE app.pagamento
    ADD CONSTRAINT FK_PAGAMENTO_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES app.cliente (id);

ALTER TABLE app.pagamento
    ADD CONSTRAINT FK_PAGAMENTO_ON_COBRANCA FOREIGN KEY (cobranca_id) REFERENCES app.cobranca (id);

ALTER TABLE app.pagamento
    ADD CONSTRAINT FK_PAGAMENTO_ON_ORGANIZACAO FOREIGN KEY (organizacao_id) REFERENCES app.organizacao (id);

ALTER TABLE app.page_component
    ADD CONSTRAINT FK_PAGE_COMPONENT_ON_PAGE FOREIGN KEY (page_id) REFERENCES app.page (id);

ALTER TABLE app.page
    ADD CONSTRAINT FK_PAGE_ON_TENANT FOREIGN KEY (tenant_id) REFERENCES app.tenant (id);

ALTER TABLE app.plano_cliente
    ADD CONSTRAINT FK_PLANO_CLIENTE_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES app.cliente (id);

ALTER TABLE app.plano_cliente
    ADD CONSTRAINT FK_PLANO_CLIENTE_ON_COBRANCA FOREIGN KEY (cobranca_id) REFERENCES app.cobranca (id);

ALTER TABLE app.plano_cliente
    ADD CONSTRAINT FK_PLANO_CLIENTE_ON_PLANO_SERVICO FOREIGN KEY (plano_servico_id) REFERENCES app.plano_servico (id);

ALTER TABLE app.plano_limites
    ADD CONSTRAINT FK_PLANO_LIMITES_ON_PLANO FOREIGN KEY (plano_id) REFERENCES app.plano (id);

ALTER TABLE app.plano_servico
    ADD CONSTRAINT FK_PLANO_SERVICO_ON_ORGANIZACAO FOREIGN KEY (organizacao_id) REFERENCES app.organizacao (id);

ALTER TABLE app.produto
    ADD CONSTRAINT FK_PRODUTO_ON_CATEGORIA FOREIGN KEY (categoria_id) REFERENCES app.categoria (id);

ALTER TABLE app.produto
    ADD CONSTRAINT FK_PRODUTO_ON_ORGANIZACAO FOREIGN KEY (organizacao_id) REFERENCES app.organizacao (id);

ALTER TABLE app.servico
    ADD CONSTRAINT FK_SERVICO_ON_CATEGORIA FOREIGN KEY (categoria_id) REFERENCES app.categoria (id);

ALTER TABLE app.servico
    ADD CONSTRAINT FK_SERVICO_ON_ORGANIZACAO FOREIGN KEY (organizacao_id) REFERENCES app.organizacao (id);

ALTER TABLE app.agendamento_funcionario
    ADD CONSTRAINT fk_agefun_on_agendamento FOREIGN KEY (agendamento_id) REFERENCES app.agendamento (id);

ALTER TABLE app.agendamento_funcionario
    ADD CONSTRAINT fk_agefun_on_funcionario FOREIGN KEY (funcionario_id) REFERENCES app.funcionario (id);

ALTER TABLE app.agendamento_servico
    ADD CONSTRAINT fk_ageser_on_agendamento FOREIGN KEY (agendamento_id) REFERENCES app.agendamento (id);

ALTER TABLE app.agendamento_servico
    ADD CONSTRAINT fk_ageser_on_servico FOREIGN KEY (servico_id) REFERENCES app.servico (id);

ALTER TABLE app.funcionario_servico
    ADD CONSTRAINT fk_funser_on_funcionario FOREIGN KEY (funcionario_id) REFERENCES app.funcionario (id);

ALTER TABLE app.funcionario_servico
    ADD CONSTRAINT fk_funser_on_servico FOREIGN KEY (servico_id) REFERENCES app.servico (id);

ALTER TABLE app.produto_como_usar
    ADD CONSTRAINT fk_produto_como_usar_on_produto FOREIGN KEY (produto_id) REFERENCES app.produto (id);

ALTER TABLE app.produto_especificacoes
    ADD CONSTRAINT fk_produto_especificacoes_on_produto FOREIGN KEY (produto_id) REFERENCES app.produto (id);

ALTER TABLE app.produto_imagens
    ADD CONSTRAINT fk_produto_imagens_on_produto FOREIGN KEY (produto_id) REFERENCES app.produto (id);

ALTER TABLE app.produto_ingredientes
    ADD CONSTRAINT fk_produto_ingredientes_on_produto FOREIGN KEY (produto_id) REFERENCES app.produto (id);

ALTER TABLE app.produto_relacionados_assoc
    ADD CONSTRAINT fk_prorelass_on_produto FOREIGN KEY (produto_id) REFERENCES app.produto (id);

ALTER TABLE app.produto_relacionados_assoc
    ADD CONSTRAINT fk_prorelass_on_relacionado FOREIGN KEY (relacionado_id) REFERENCES app.produto (id);

ALTER TABLE app.produto_utilizados_assoc
    ADD CONSTRAINT fk_proutiass_on_produto FOREIGN KEY (produto_id) REFERENCES app.produto (id);

ALTER TABLE app.produto_utilizados_assoc
    ADD CONSTRAINT fk_proutiass_on_utilizado FOREIGN KEY (utilizado_id) REFERENCES app.produto (id);

ALTER TABLE app.servico_imagens
    ADD CONSTRAINT fk_servico_imagens_on_servico FOREIGN KEY (servico_id) REFERENCES app.servico (id);

ALTER TABLE app.servico_produtos
    ADD CONSTRAINT fk_servico_produtos_on_servico FOREIGN KEY (servico_id) REFERENCES app.servico (id);
