CREATE SEQUENCE IF NOT EXISTS agendamento_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS bloqueio_agenda_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS cargo_funcionario_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS cartao_credito_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS categoria_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS cliente_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS cobranca_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS compra_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS compra_produto_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS "config-sistema_id_seq" START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS dados_faturamento_organizacao_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS endereco_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS funcionario_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS horario_trabalho_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS jornada_dia_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS jornada_trabalho_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS organizacao_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS pagamento_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS page_component_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS page_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS plano_cliente_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS plano_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS plano_limites_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS plano_servico_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS produto_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS servico_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS tb_roles_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS tenant_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE agendamento
(
    cliente_id     BIGINT                                  NOT NULL,
    dt_agendamento TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    dt_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    dt_criacao     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id BIGINT                                  NOT NULL,
    observacao     TEXT,
    status         VARCHAR(255)                            NOT NULL,
    CONSTRAINT agendamento_pkey PRIMARY KEY (id)
);

CREATE TABLE agendamento_funcionario
(
    agendamento_id BIGINT NOT NULL,
    funcionario_id BIGINT NOT NULL
);

CREATE TABLE agendamento_servico
(
    agendamento_id BIGINT NOT NULL,
    servico_id     BIGINT NOT NULL
);

CREATE TABLE bloqueio_agenda
(
    agendamento_id  BIGINT,
    fim_bloqueio    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    funcionario_id  BIGINT                                  NOT NULL,
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    inicio_bloqueio TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    descricao       VARCHAR(255),
    tipo_bloqueio   VARCHAR(255)                            NOT NULL,
    CONSTRAINT bloqueio_agenda_pkey PRIMARY KEY (id)
);

CREATE TABLE cargo_funcionario
(
    ativo          BOOLEAN,
    data_criacao   TIMESTAMP WITHOUT TIME ZONE,
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id BIGINT                                  NOT NULL,
    nome           VARCHAR(100)                            NOT NULL,
    descricao      VARCHAR(500),
    CONSTRAINT cargo_funcionario_pkey PRIMARY KEY (id)
);

CREATE TABLE cartao_credito
(
    ativo           BOOLEAN                                 NOT NULL,
    cvv             VARCHAR(4)                              NOT NULL,
    is_principal    BOOLEAN                                 NOT NULL,
    data_vencimento VARCHAR(7)                              NOT NULL,
    cliente_id      BIGINT                                  NOT NULL,
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    numero_cartao   VARCHAR(19)                             NOT NULL,
    bandeira        VARCHAR(20)                             NOT NULL,
    apelido         VARCHAR(50),
    nome_portador   VARCHAR(100)                            NOT NULL,
    CONSTRAINT cartao_credito_pkey PRIMARY KEY (id)
);

CREATE TABLE categoria
(
    ativo          BOOLEAN                                 NOT NULL,
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id BIGINT                                  NOT NULL,
    tipo           VARCHAR(50)                             NOT NULL,
    label          VARCHAR(255)                            NOT NULL,
    value          VARCHAR(255)                            NOT NULL,
    CONSTRAINT categoria_pkey PRIMARY KEY (id)
);

CREATE TABLE cliente
(
    ativo                  BOOLEAN                                 NOT NULL,
    data_nascimento        date,
    is_cadastro_incompleto BOOLEAN,
    dt_criacao             TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id         BIGINT                                  NOT NULL,
    cpf                    VARCHAR(14),
    telefone               VARCHAR(15),
    email                  VARCHAR(255)                            NOT NULL,
    nome_completo          VARCHAR(255)                            NOT NULL,
    password               VARCHAR(255)                            NOT NULL,
    role                   VARCHAR(255),
    username               VARCHAR(255)                            NOT NULL,
    CONSTRAINT cliente_pkey PRIMARY KEY (id)
);

CREATE TABLE cobranca
(
    dt_vencimento         date,
    juros_atraso          numeric(5, 2),
    multa_atraso          numeric(10, 2),
    permite_parcelamento  BOOLEAN,
    valor                 numeric(10, 2)                          NOT NULL,
    valor_pago            numeric(10, 2),
    valor_pendente        numeric(10, 2),
    agendamento_id        BIGINT,
    cliente_id            BIGINT                                  NOT NULL,
    compra_id             BIGINT,
    dt_atualizacao        TIMESTAMP WITHOUT TIME ZONE,
    dt_criacao            TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    dt_pagamento_completo TIMESTAMP WITHOUT TIME ZONE,
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id        BIGINT                                  NOT NULL,
    numero_cobranca       VARCHAR(20),
    tipo_cobranca         VARCHAR(30)                             NOT NULL,
    status_cobranca       VARCHAR(50)                             NOT NULL,
    observacoes           TEXT,
    CONSTRAINT cobranca_pkey PRIMARY KEY (id)
);

CREATE TABLE compra
(
    valor_desconto numeric(10, 2),
    valor_final    numeric(10, 2)                          NOT NULL,
    valor_total    numeric(10, 2)                          NOT NULL,
    cliente_id     BIGINT                                  NOT NULL,
    dt_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    dt_criacao     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    dt_finalizacao TIMESTAMP WITHOUT TIME ZONE,
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id BIGINT                                  NOT NULL,
    numero_pedido  VARCHAR(20),
    tipo_compra    VARCHAR(30)                             NOT NULL,
    status_compra  VARCHAR(50)                             NOT NULL,
    observacoes    TEXT,
    CONSTRAINT compra_pkey PRIMARY KEY (id)
);

CREATE TABLE compra_produto
(
    desconto_item  numeric(10, 2),
    preco_unitario numeric(10, 2)                          NOT NULL,
    quantidade     INTEGER                                 NOT NULL,
    subtotal       numeric(10, 2)                          NOT NULL,
    compra_id      BIGINT                                  NOT NULL,
    dt_adicionado  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    produto_id     BIGINT                                  NOT NULL,
    observacoes    TEXT,
    CONSTRAINT compra_produto_pkey PRIMARY KEY (id)
);

CREATE TABLE "config-sistema"
(
    dispara_notificacoes_push BOOLEAN                                 NOT NULL,
    usa_ecommerce             BOOLEAN                                 NOT NULL,
    usa_gestao_produtos       BOOLEAN                                 NOT NULL,
    usa_planos_para_clientes  BOOLEAN                                 NOT NULL,
    dt_atualizacao            TIMESTAMP WITHOUT TIME ZONE,
    dt_criacao                TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id            BIGINT                                  NOT NULL,
    CONSTRAINT "config-sistema_pkey" PRIMARY KEY (id)
);

CREATE TABLE dados_faturamento_organizacao
(
    ativo              BOOLEAN                                 NOT NULL,
    conta_verificador  VARCHAR(2),
    dt_validade_cartao date,
    dt_atualizacao     TIMESTAMP WITHOUT TIME ZONE,
    dt_cadastro        TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id     BIGINT                                  NOT NULL,
    agencia            VARCHAR(10),
    cpf_cnpj           VARCHAR(18),
    numero_cartao      VARCHAR(19),
    conta_numero       VARCHAR(20),
    CONSTRAINT dados_faturamento_organizacao_pkey PRIMARY KEY (id)
);

CREATE TABLE endereco
(
    ativo        BOOLEAN                                 NOT NULL,
    is_principal BOOLEAN                                 NOT NULL,
    uf           VARCHAR(2)                              NOT NULL,
    cliente_id   BIGINT                                  NOT NULL,
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cep          VARCHAR(10)                             NOT NULL,
    numero       VARCHAR(20)                             NOT NULL,
    tipo         VARCHAR(20),
    bairro       VARCHAR(100)                            NOT NULL,
    cidade       VARCHAR(100)                            NOT NULL,
    complemento  VARCHAR(255),
    logradouro   VARCHAR(255)                            NOT NULL,
    referencia   TEXT,
    CONSTRAINT endereco_pkey PRIMARY KEY (id)
);

-- CREATE TABLE flyway_schema_history
-- (
--     installed_rank INTEGER                                   NOT NULL,
--     version        VARCHAR(50),
--     description    VARCHAR(200)                              NOT NULL,
--     type           VARCHAR(20)                               NOT NULL,
--     script         VARCHAR(1000)                             NOT NULL,
--     checksum       INTEGER,
--     installed_by   VARCHAR(100)                              NOT NULL,
--     installed_on   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
--     execution_time INTEGER                                   NOT NULL,
--     success        BOOLEAN                                   NOT NULL,
--     CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
-- );

CREATE TABLE funcionario
(
    ativo              BOOLEAN                                 NOT NULL,
    data_nasc          date,
    is_comissao        BOOLEAN,
    is_visivel_externo BOOLEAN,
    nivel              INTEGER,
    salario            numeric(10, 2),
    uf                 VARCHAR(2),
    data_contratacao   TIMESTAMP WITHOUT TIME ZONE,
    data_criacao       TIMESTAMP WITHOUT TIME ZONE,
    data_update        TIMESTAMP WITHOUT TIME ZONE,
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id     BIGINT                                  NOT NULL,
    categ_habilitacao  VARCHAR(10),
    cep                VARCHAR(10),
    cpf                VARCHAR(14),
    agencia            VARCHAR(20),
    cnh                VARCHAR(20),
    ctps_serie         VARCHAR(20),
    numero             VARCHAR(20),
    operacao           VARCHAR(20),
    rg                 VARCHAR(20),
    sexo               VARCHAR(20),
    telefone           VARCHAR(20),
    cargo              VARCHAR(30),
    cert_militar       VARCHAR(30),
    conta              VARCHAR(30),
    ctps               VARCHAR(30),
    pis_pasep          VARCHAR(30),
    titulo_eleitor     VARCHAR(30),
    comissao           VARCHAR(50),
    estado_civil       VARCHAR(50),
    jornada_semanal    VARCHAR(50),
    rg_org_emissor     VARCHAR(50),
    situacao           VARCHAR(50),
    apelido            VARCHAR(100),
    bairro             VARCHAR(100),
    banco              VARCHAR(100),
    cidade             VARCHAR(100),
    grau_instrucao     VARCHAR(100),
    naturalidade       VARCHAR(100),
    complemento        VARCHAR(255),
    email              VARCHAR(255)                            NOT NULL,
    formacao           TEXT,
    foto               VARCHAR(255),
    logradouro         VARCHAR(255),
    nome_completo      VARCHAR(255)                            NOT NULL,
    nome_mae           VARCHAR(255),
    nome_pai           VARCHAR(255),
    password           VARCHAR(255)                            NOT NULL,
    role               VARCHAR(255),
    username           VARCHAR(255)                            NOT NULL,
    CONSTRAINT funcionario_pkey PRIMARY KEY (id)
);

CREATE TABLE funcionario_servico
(
    funcionario_id BIGINT NOT NULL,
    servico_id     BIGINT NOT NULL
);

CREATE TABLE horario_trabalho
(
    hora_fim       time WITHOUT TIME ZONE                  NOT NULL,
    hora_inicio    time WITHOUT TIME ZONE                  NOT NULL,
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    jornada_dia_id BIGINT                                  NOT NULL,
    CONSTRAINT horario_trabalho_pkey PRIMARY KEY (id)
);

CREATE TABLE jornada_dia
(
    ativo          BOOLEAN                                 NOT NULL,
    funcionario_id BIGINT                                  NOT NULL,
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dia_semana     VARCHAR(255)                            NOT NULL,
    CONSTRAINT jornada_dia_pkey PRIMARY KEY (id)
);

CREATE TABLE jornada_trabalho
(
    ativo          BOOLEAN,
    hora_fim       time WITHOUT TIME ZONE                  NOT NULL,
    hora_inicio    time WITHOUT TIME ZONE                  NOT NULL,
    funcionario_id BIGINT                                  NOT NULL,
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dia_semana     VARCHAR(255)                            NOT NULL,
    CONSTRAINT jornada_trabalho_pkey PRIMARY KEY (id)
);

CREATE TABLE organizacao
(
    ativo                     BOOLEAN                                 NOT NULL,
    dt_atualizacao            TIMESTAMP WITHOUT TIME ZONE,
    dt_cadastro               TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    endereco_principal_id     BIGINT,
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    limites_personalizados_id BIGINT,
    plano_id                  BIGINT                                  NOT NULL,
    cpf_responsavel           VARCHAR(14)                             NOT NULL,
    cnpj                      VARCHAR(18)                             NOT NULL,
    email_responsavel         VARCHAR(255)                            NOT NULL,
    nome                      VARCHAR(255)                            NOT NULL,
    nome_fantasia             VARCHAR(255),
    nome_responsavel          VARCHAR(255)                            NOT NULL,
    CONSTRAINT organizacao_pkey PRIMARY KEY (id)
);

CREATE TABLE pagamento
(
    valor             numeric(10, 2)                          NOT NULL,
    cartao_credito_id BIGINT,
    cliente_id        BIGINT                                  NOT NULL,
    cobranca_id       BIGINT                                  NOT NULL,
    data_pagamento    TIMESTAMP WITHOUT TIME ZONE,
    dt_atualizacao    TIMESTAMP WITHOUT TIME ZONE,
    dt_criacao        TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_pagamento  VARCHAR(20)                             NOT NULL,
    metodo_pagamento  VARCHAR(50)                             NOT NULL,
    comprovante_url   VARCHAR(500),
    observacoes       TEXT,
    transacao_id      VARCHAR(255),
    CONSTRAINT pagamento_pkey PRIMARY KEY (id)
);

CREATE TABLE page
(
    active           BOOLEAN                                 NOT NULL,
    dt_atualizacao   TIMESTAMP WITHOUT TIME ZONE,
    dt_criacao       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id        BIGINT                                  NOT NULL,
    slug             VARCHAR(100)                            NOT NULL,
    description      TEXT,
    meta_description TEXT,
    meta_keywords    TEXT,
    meta_title       VARCHAR(255),
    title            VARCHAR(255)                            NOT NULL,
    CONSTRAINT page_pkey PRIMARY KEY (id)
);

CREATE TABLE page_component
(
    active         BOOLEAN                                 NOT NULL,
    order_index    INTEGER                                 NOT NULL,
    dt_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    dt_criacao     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    page_id        BIGINT                                  NOT NULL,
    type           VARCHAR(50)                             NOT NULL,
    style_config   TEXT,
    props_json     TEXT,
    CONSTRAINT page_component_pkey PRIMARY KEY (id)
);

CREATE TABLE plano
(
    ativo                BOOLEAN                                 NOT NULL,
    valor_unitario       numeric(10, 2)                          NOT NULL,
    data_ultima_cobranca TIMESTAMP WITHOUT TIME ZONE,
    dia_cobranca         TIMESTAMP WITHOUT TIME ZONE,
    dt_atualizacao       TIMESTAMP WITHOUT TIME ZONE,
    dt_criacao           TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    recorrencia          VARCHAR(50)                             NOT NULL,
    nome                 VARCHAR(100)                            NOT NULL,
    descricao            TEXT,
    CONSTRAINT plano_pkey PRIMARY KEY (id)
);

CREATE TABLE plano_cliente
(
    cliente_id       BIGINT                                  NOT NULL,
    cobranca_id      BIGINT,
    dt_fim           TIMESTAMP WITHOUT TIME ZONE,
    dt_inicio        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    plano_servico_id BIGINT                                  NOT NULL,
    status           VARCHAR(50)                             NOT NULL,
    CONSTRAINT plano_cliente_pkey PRIMARY KEY (id)
);

CREATE TABLE plano_limites
(
    limite_agendamento   INTEGER,
    limite_cliente       INTEGER,
    limite_colaborador   INTEGER,
    permite_landing_page BOOLEAN,
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    plano_id             BIGINT                                  NOT NULL,
    CONSTRAINT plano_limites_pkey PRIMARY KEY (id)
);

CREATE TABLE plano_servico
(
    ativo          BOOLEAN                                 NOT NULL,
    preco          numeric(10, 2)                          NOT NULL,
    validade_dias  INTEGER,
    dt_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    dt_criacao     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id BIGINT                                  NOT NULL,
    nome           VARCHAR(100)                            NOT NULL,
    descricao      TEXT,
    CONSTRAINT plano_servico_pkey PRIMARY KEY (id)
);

CREATE TABLE produto
(
    ativo               BOOLEAN                                 NOT NULL,
    avaliacao           numeric(3, 2),
    desconto_percentual INTEGER,
    destaque            BOOLEAN                                 NOT NULL,
    estoque_minimo      INTEGER,
    peso_kg             numeric(8, 3),
    preco               numeric(10, 2)                          NOT NULL,
    preco_custo         numeric(10, 2),
    quantidade_estoque  INTEGER,
    total_avaliacoes    INTEGER,
    categoria_id        BIGINT                                  NOT NULL,
    dt_atualizacao      TIMESTAMP WITHOUT TIME ZONE,
    dt_criacao          TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id      BIGINT                                  NOT NULL,
    unidade             VARCHAR(10),
    codigo_barras       VARCHAR(50),
    codigo_interno      VARCHAR(50),
    modelo              VARCHAR(50),
    genero              VARCHAR(100),
    marca               VARCHAR(100),
    usuario_atualizacao VARCHAR(100),
    usuario_criacao     VARCHAR(100),
    descricao           TEXT,
    nome                VARCHAR(255)                            NOT NULL,
    status_produto      VARCHAR(255)                            NOT NULL,
    CONSTRAINT produto_pkey PRIMARY KEY (id)
);

CREATE TABLE produto_como_usar
(
    passo_ordem INTEGER NOT NULL,
    produto_id  BIGINT  NOT NULL,
    passo       TEXT    NOT NULL,
    CONSTRAINT produto_como_usar_pkey PRIMARY KEY (passo_ordem, produto_id)
);

CREATE TABLE produto_especificacoes
(
    produto_id BIGINT       NOT NULL,
    chave      VARCHAR(100) NOT NULL,
    valor      TEXT,
    CONSTRAINT produto_especificacoes_pkey PRIMARY KEY (produto_id, chave)
);

CREATE TABLE produto_imagens
(
    produto_id BIGINT        NOT NULL,
    url_imagem VARCHAR(1000) NOT NULL
);

CREATE TABLE produto_ingredientes
(
    produto_id  BIGINT NOT NULL,
    ingrediente TEXT   NOT NULL
);

CREATE TABLE produto_relacionados_assoc
(
    produto_id     BIGINT NOT NULL,
    relacionado_id BIGINT NOT NULL,
    CONSTRAINT produto_relacionados_assoc_pkey PRIMARY KEY (produto_id, relacionado_id)
);

CREATE TABLE produto_utilizados_assoc
(
    produto_id   BIGINT NOT NULL,
    utilizado_id BIGINT NOT NULL,
    CONSTRAINT produto_utilizados_assoc_pkey PRIMARY KEY (produto_id, utilizado_id)
);

CREATE TABLE servico
(
    ativo                  BOOLEAN                                 NOT NULL,
    desconto               INTEGER,
    is_avaliacao           BOOLEAN                                 NOT NULL,
    is_home                BOOLEAN,
    preco                  numeric(10, 2)                          NOT NULL,
    tempo_estimado_minutos INTEGER                                 NOT NULL,
    categoria_id           BIGINT                                  NOT NULL,
    dt_atualizacao         TIMESTAMP WITHOUT TIME ZONE,
    dt_criacao             TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id         BIGINT                                  NOT NULL,
    descricao              TEXT,
    genero                 VARCHAR(255)                            NOT NULL,
    nome                   VARCHAR(255)                            NOT NULL,
    usuario_atualizacao    VARCHAR(255),
    CONSTRAINT servico_pkey PRIMARY KEY (id)
);

CREATE TABLE servico_imagens
(
    servico_id BIGINT        NOT NULL,
    url_imagem VARCHAR(1000) NOT NULL
);

CREATE TABLE servico_produtos
(
    servico_id   BIGINT       NOT NULL,
    produto_nome VARCHAR(255) NOT NULL
);

CREATE TABLE tb_roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(255)                            NOT NULL,
    CONSTRAINT tb_roles_pkey PRIMARY KEY (id)
);

CREATE TABLE tenant
(
    active         BOOLEAN                                 NOT NULL,
    dt_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    dt_criacao     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    theme          VARCHAR(50),
    subdomain      VARCHAR(100)                            NOT NULL,
    description    TEXT,
    email          VARCHAR(255),
    name           VARCHAR(255)                            NOT NULL,
    theme_config   TEXT,
    CONSTRAINT tenant_pkey PRIMARY KEY (id)
);

ALTER TABLE bloqueio_agenda
    ADD CONSTRAINT bloqueio_agenda_agendamento_id_key UNIQUE (agendamento_id);

ALTER TABLE cliente
    ADD CONSTRAINT cliente_email_key UNIQUE (email);

ALTER TABLE cliente
    ADD CONSTRAINT cliente_username_key UNIQUE (username);

ALTER TABLE cobranca
    ADD CONSTRAINT cobranca_agendamento_id_key UNIQUE (agendamento_id);

ALTER TABLE cobranca
    ADD CONSTRAINT cobranca_compra_id_key UNIQUE (compra_id);

ALTER TABLE cobranca
    ADD CONSTRAINT cobranca_numero_cobranca_key UNIQUE (numero_cobranca);

ALTER TABLE compra
    ADD CONSTRAINT compra_numero_pedido_key UNIQUE (numero_pedido);

ALTER TABLE "config-sistema"
    ADD CONSTRAINT "config-sistema_organizacao_id_key" UNIQUE (organizacao_id);

ALTER TABLE dados_faturamento_organizacao
    ADD CONSTRAINT dados_faturamento_organizacao_organizacao_id_key UNIQUE (organizacao_id);

ALTER TABLE funcionario
    ADD CONSTRAINT funcionario_email_key UNIQUE (email);

ALTER TABLE funcionario
    ADD CONSTRAINT funcionario_username_key UNIQUE (username);

ALTER TABLE page
    ADD CONSTRAINT idx_page_tenant_slug UNIQUE (tenant_id, slug);

ALTER TABLE organizacao
    ADD CONSTRAINT organizacao_cnpj_key UNIQUE (cnpj);

ALTER TABLE organizacao
    ADD CONSTRAINT organizacao_cpf_responsavel_key UNIQUE (cpf_responsavel);

ALTER TABLE organizacao
    ADD CONSTRAINT organizacao_email_responsavel_key UNIQUE (email_responsavel);

ALTER TABLE organizacao
    ADD CONSTRAINT organizacao_endereco_principal_id_key UNIQUE (endereco_principal_id);

ALTER TABLE organizacao
    ADD CONSTRAINT organizacao_limites_personalizados_id_key UNIQUE (limites_personalizados_id);

ALTER TABLE organizacao
    ADD CONSTRAINT organizacao_nome_key UNIQUE (nome);

ALTER TABLE plano_cliente
    ADD CONSTRAINT plano_cliente_cobranca_id_key UNIQUE (cobranca_id);

ALTER TABLE plano_limites
    ADD CONSTRAINT plano_limites_plano_id_key UNIQUE (plano_id);

ALTER TABLE plano
    ADD CONSTRAINT plano_nome_key UNIQUE (nome);

ALTER TABLE produto
    ADD CONSTRAINT produto_codigo_interno_key UNIQUE (codigo_interno);

ALTER TABLE tb_roles
    ADD CONSTRAINT tb_roles_nome_key UNIQUE (nome);

ALTER TABLE tenant
    ADD CONSTRAINT tenant_subdomain_key UNIQUE (subdomain);

-- CREATE INDEX flyway_schema_history_s_idx ON flyway_schema_history (success);

CREATE INDEX idx_component_page_order ON page_component (page_id, order_index);

ALTER TABLE servico_produtos
    ADD CONSTRAINT fk2cr08codwc530o2sa763prmvp FOREIGN KEY (servico_id) REFERENCES servico (id) ON DELETE NO ACTION;

ALTER TABLE organizacao
    ADD CONSTRAINT fk2xhjfwo902xy0hi7456iqs772 FOREIGN KEY (limites_personalizados_id) REFERENCES plano_limites (id) ON DELETE NO ACTION;

ALTER TABLE agendamento_funcionario
    ADD CONSTRAINT fk3cpwccxuoaco96mt8jto7f71v FOREIGN KEY (agendamento_id) REFERENCES agendamento (id) ON DELETE NO ACTION;

ALTER TABLE servico
    ADD CONSTRAINT fk3s3u441gpubcnj5g69hqim1p3 FOREIGN KEY (categoria_id) REFERENCES categoria (id) ON DELETE NO ACTION;

ALTER TABLE produto_relacionados_assoc
    ADD CONSTRAINT fk3smdr4alolte28448v49xl0du FOREIGN KEY (produto_id) REFERENCES produto (id) ON DELETE NO ACTION;

ALTER TABLE produto
    ADD CONSTRAINT fk3x9d3ekag2i23qxt9q60a97m2 FOREIGN KEY (organizacao_id) REFERENCES organizacao (id) ON DELETE NO ACTION;

ALTER TABLE cliente
    ADD CONSTRAINT fk4no3jte1i4v63546trxrmkc7v FOREIGN KEY (organizacao_id) REFERENCES organizacao (id) ON DELETE NO ACTION;

ALTER TABLE organizacao
    ADD CONSTRAINT fk4uoda6xl50a2j1yac0gc9uck5 FOREIGN KEY (endereco_principal_id) REFERENCES endereco (id) ON DELETE NO ACTION;

ALTER TABLE produto_relacionados_assoc
    ADD CONSTRAINT fk5dgxhbxu85y1cgqm0ca1vafy3 FOREIGN KEY (relacionado_id) REFERENCES produto (id) ON DELETE NO ACTION;

ALTER TABLE cobranca
    ADD CONSTRAINT fk5vd0r9wuxdq5nkdc8hvh5uy9h FOREIGN KEY (cliente_id) REFERENCES cliente (id) ON DELETE NO ACTION;

ALTER TABLE cartao_credito
    ADD CONSTRAINT fk63b7u4hqruddl19wlbg8fqdf2 FOREIGN KEY (cliente_id) REFERENCES cliente (id) ON DELETE NO ACTION;

ALTER TABLE plano_servico
    ADD CONSTRAINT fk63f7vjv4vnee753nuscfmo5ve FOREIGN KEY (organizacao_id) REFERENCES organizacao (id) ON DELETE NO ACTION;

ALTER TABLE compra_produto
    ADD CONSTRAINT fk74m4wbumrnao6bnoglcqleqko FOREIGN KEY (produto_id) REFERENCES produto (id) ON DELETE NO ACTION;

ALTER TABLE pagamento
    ADD CONSTRAINT fk8fh46wc82qvy6h0sny4g72ymk FOREIGN KEY (cliente_id) REFERENCES cliente (id) ON DELETE NO ACTION;

ALTER TABLE funcionario
    ADD CONSTRAINT fk8g266xe7wnaf6epkdv9a4sjii FOREIGN KEY (organizacao_id) REFERENCES organizacao (id) ON DELETE NO ACTION;

ALTER TABLE endereco
    ADD CONSTRAINT fk8s7ivtl4foyhrfam9xqom73n9 FOREIGN KEY (cliente_id) REFERENCES cliente (id) ON DELETE NO ACTION;

ALTER TABLE plano_limites
    ADD CONSTRAINT fk8v6sjv576retuobqtfpe380yy FOREIGN KEY (plano_id) REFERENCES plano (id) ON DELETE NO ACTION;

ALTER TABLE produto_utilizados_assoc
    ADD CONSTRAINT fk93cd9mppripg73gy9cfgsplpn FOREIGN KEY (utilizado_id) REFERENCES produto (id) ON DELETE NO ACTION;

ALTER TABLE agendamento_servico
    ADD CONSTRAINT fk9fujots3a3pydg7pogni24sjp FOREIGN KEY (servico_id) REFERENCES servico (id) ON DELETE NO ACTION;

ALTER TABLE jornada_trabalho
    ADD CONSTRAINT fk9sny47ckrs0km2umjxisrc1bk FOREIGN KEY (funcionario_id) REFERENCES funcionario (id) ON DELETE NO ACTION;

ALTER TABLE page_component
    ADD CONSTRAINT fka0acy0o6qsqk3x5gpoewocab3 FOREIGN KEY (page_id) REFERENCES page (id) ON DELETE NO ACTION;

ALTER TABLE jornada_dia
    ADD CONSTRAINT fkas8m50r6did8mw2rdi7ikgssf FOREIGN KEY (funcionario_id) REFERENCES funcionario (id) ON DELETE NO ACTION;

ALTER TABLE funcionario_servico
    ADD CONSTRAINT fkbi8i9o8qmyegdskpsmq9iyc8h FOREIGN KEY (servico_id) REFERENCES servico (id) ON DELETE NO ACTION;

ALTER TABLE plano_cliente
    ADD CONSTRAINT fkbpshhi8x19nduenjhsmckjwms FOREIGN KEY (cliente_id) REFERENCES cliente (id) ON DELETE NO ACTION;

ALTER TABLE produto_especificacoes
    ADD CONSTRAINT fkc23cpseet2xbxh6jpumpajyag FOREIGN KEY (produto_id) REFERENCES produto (id) ON DELETE NO ACTION;

ALTER TABLE servico
    ADD CONSTRAINT fkcmhegaytja0yvg1py0tl5o9e7 FOREIGN KEY (organizacao_id) REFERENCES organizacao (id) ON DELETE NO ACTION;

ALTER TABLE funcionario_servico
    ADD CONSTRAINT fkcupx11qjtt36igwo8fw1h8sh2 FOREIGN KEY (funcionario_id) REFERENCES funcionario (id) ON DELETE NO ACTION;

ALTER TABLE organizacao
    ADD CONSTRAINT fkdhfrsrrcj4l51tmv12y338lgf FOREIGN KEY (plano_id) REFERENCES plano (id) ON DELETE NO ACTION;

ALTER TABLE servico_imagens
    ADD CONSTRAINT fkdnk7c5u5vxu4o8ofcbwultti9 FOREIGN KEY (servico_id) REFERENCES servico (id) ON DELETE NO ACTION;

ALTER TABLE cobranca
    ADD CONSTRAINT fkenn7k6qaxlw02i3ek16q0xmn7 FOREIGN KEY (compra_id) REFERENCES compra (id) ON DELETE NO ACTION;

ALTER TABLE page
    ADD CONSTRAINT fkep6tw9ca76g4wy5b98fhmg5pb FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE NO ACTION;

ALTER TABLE "config-sistema"
    ADD CONSTRAINT fkg29xdjiii7ju7sq7af3am5ay6 FOREIGN KEY (organizacao_id) REFERENCES organizacao (id) ON DELETE NO ACTION;

ALTER TABLE produto_imagens
    ADD CONSTRAINT fkg8laoe7wod2vuf03jn914tuli FOREIGN KEY (produto_id) REFERENCES produto (id) ON DELETE NO ACTION;

ALTER TABLE pagamento
    ADD CONSTRAINT fkgwqjpv1iuspv5uobgpopqd9au FOREIGN KEY (cartao_credito_id) REFERENCES cartao_credito (id) ON DELETE NO ACTION;

ALTER TABLE horario_trabalho
    ADD CONSTRAINT fkhhctyfgex2eukfwde7nmy781e FOREIGN KEY (jornada_dia_id) REFERENCES jornada_dia (id) ON DELETE NO ACTION;

ALTER TABLE agendamento
    ADD CONSTRAINT fkj7esxn2b0np1r5q0ot8fugrjn FOREIGN KEY (organizacao_id) REFERENCES organizacao (id) ON DELETE NO ACTION;

ALTER TABLE cobranca
    ADD CONSTRAINT fkjipuwkvr6xblno17o09snnyhy FOREIGN KEY (agendamento_id) REFERENCES agendamento (id) ON DELETE NO ACTION;

ALTER TABLE dados_faturamento_organizacao
    ADD CONSTRAINT fkk6a8vwph575qr4b4r6xdgyy6c FOREIGN KEY (organizacao_id) REFERENCES organizacao (id) ON DELETE NO ACTION;

ALTER TABLE produto_ingredientes
    ADD CONSTRAINT fkkjeqgrqt9g7watncaiocd9xb7 FOREIGN KEY (produto_id) REFERENCES produto (id) ON DELETE NO ACTION;

ALTER TABLE agendamento_funcionario
    ADD CONSTRAINT fkli8p8wa439bg9f9m0818ps397 FOREIGN KEY (funcionario_id) REFERENCES funcionario (id) ON DELETE NO ACTION;

ALTER TABLE compra_produto
    ADD CONSTRAINT fkmd4lj0wl5u21so1rm0bt0nnvr FOREIGN KEY (compra_id) REFERENCES compra (id) ON DELETE NO ACTION;

ALTER TABLE cobranca
    ADD CONSTRAINT fkmnn1n6irnir653p1xl6kjdiba FOREIGN KEY (organizacao_id) REFERENCES organizacao (id) ON DELETE NO ACTION;

ALTER TABLE compra
    ADD CONSTRAINT fkni21w35sfgo033m8l93ki11ab FOREIGN KEY (cliente_id) REFERENCES cliente (id) ON DELETE NO ACTION;

ALTER TABLE produto_como_usar
    ADD CONSTRAINT fko127vpyccsujypakv5okek972 FOREIGN KEY (produto_id) REFERENCES produto (id) ON DELETE NO ACTION;

ALTER TABLE cargo_funcionario
    ADD CONSTRAINT fko96j1rg6in1rxa7y1gbbo752d FOREIGN KEY (organizacao_id) REFERENCES organizacao (id) ON DELETE NO ACTION;

ALTER TABLE produto
    ADD CONSTRAINT fkopu9jggwnamfv0c8k2ri3kx0a FOREIGN KEY (categoria_id) REFERENCES categoria (id) ON DELETE NO ACTION;

ALTER TABLE categoria
    ADD CONSTRAINT fkpcrxr3aluaeojr8txyt3a3q5q FOREIGN KEY (organizacao_id) REFERENCES organizacao (id) ON DELETE NO ACTION;

ALTER TABLE bloqueio_agenda
    ADD CONSTRAINT fkq203134jhobdyhkfxwp318dd3 FOREIGN KEY (agendamento_id) REFERENCES agendamento (id) ON DELETE NO ACTION;

ALTER TABLE agendamento_servico
    ADD CONSTRAINT fkqma90mmn13q2vc4oe72764xt5 FOREIGN KEY (agendamento_id) REFERENCES agendamento (id) ON DELETE NO ACTION;

ALTER TABLE compra
    ADD CONSTRAINT fkqsxyq2ow9swrhhmtksq24i9gn FOREIGN KEY (organizacao_id) REFERENCES organizacao (id) ON DELETE NO ACTION;

ALTER TABLE produto_utilizados_assoc
    ADD CONSTRAINT fkr6er10npes6o43lo27n0bmibh FOREIGN KEY (produto_id) REFERENCES produto (id) ON DELETE NO ACTION;

ALTER TABLE plano_cliente
    ADD CONSTRAINT fkrike603tdjc51c7fhrpvtc340 FOREIGN KEY (plano_servico_id) REFERENCES plano_servico (id) ON DELETE NO ACTION;

ALTER TABLE plano_cliente
    ADD CONSTRAINT fkse1amhocqtvrqfbqbnier35mf FOREIGN KEY (cobranca_id) REFERENCES cobranca (id) ON DELETE NO ACTION;

ALTER TABLE agendamento
    ADD CONSTRAINT fksgdo4l8yts964f089m6ujyuef FOREIGN KEY (cliente_id) REFERENCES cliente (id) ON DELETE NO ACTION;

ALTER TABLE bloqueio_agenda
    ADD CONSTRAINT fksh34l0w4t5m7buav2juo3sk7d FOREIGN KEY (funcionario_id) REFERENCES funcionario (id) ON DELETE NO ACTION;

ALTER TABLE pagamento
    ADD CONSTRAINT fktdhcbysovleb81b140dhypq9o FOREIGN KEY (cobranca_id) REFERENCES cobranca (id) ON DELETE NO ACTION;
