-- =====================================================
-- V21: Tracking Analytics para site bellory.com.br
-- =====================================================

-- Usar schema 'site' para tabelas de tracking do site publico
SET search_path TO site;

-- 1. Tabela de visitantes unicos
CREATE TABLE site.tracking_visitors (
    id UUID PRIMARY KEY,
    first_seen_at TIMESTAMP NOT NULL DEFAULT NOW(),
    last_seen_at TIMESTAMP NOT NULL DEFAULT NOW(),
    total_sessions INTEGER DEFAULT 1,
    total_page_views INTEGER DEFAULT 0,
    is_converted BOOLEAN DEFAULT FALSE,
    converted_at TIMESTAMP,
    conversion_plan_id VARCHAR(50),
    country VARCHAR(100),
    state VARCHAR(100),
    city VARCHAR(100),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_tracking_visitors_first_seen ON site.tracking_visitors(first_seen_at);
CREATE INDEX idx_tracking_visitors_converted ON site.tracking_visitors(is_converted);

-- 2. Tabela de sessoes
CREATE TABLE site.tracking_sessions (
    id UUID PRIMARY KEY,
    visitor_id UUID NOT NULL REFERENCES site.tracking_visitors(id),
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP,
    duration_ms INTEGER DEFAULT 0,
    page_count INTEGER DEFAULT 0,
    entry_page VARCHAR(500) NOT NULL,
    exit_page VARCHAR(500),
    traffic_source VARCHAR(50) NOT NULL,
    referrer TEXT,
    utm_source VARCHAR(255),
    utm_medium VARCHAR(255),
    utm_campaign VARCHAR(255),
    utm_term VARCHAR(255),
    utm_content VARCHAR(255),
    device_type VARCHAR(20) NOT NULL,
    os VARCHAR(100),
    browser VARCHAR(100),
    screen_size VARCHAR(20),
    viewport_size VARCHAR(20),
    touch_enabled BOOLEAN DEFAULT FALSE,
    language VARCHAR(10),
    country VARCHAR(100),
    state VARCHAR(100),
    city VARCHAR(100),
    is_bounce BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_tracking_sessions_visitor ON site.tracking_sessions(visitor_id);
CREATE INDEX idx_tracking_sessions_started ON site.tracking_sessions(started_at);
CREATE INDEX idx_tracking_sessions_traffic ON site.tracking_sessions(traffic_source);
CREATE INDEX idx_tracking_sessions_entry ON site.tracking_sessions(entry_page);

-- 3. Tabela de page views
CREATE TABLE site.tracking_page_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES site.tracking_sessions(id),
    visitor_id UUID NOT NULL REFERENCES site.tracking_visitors(id),
    path VARCHAR(500) NOT NULL,
    title TEXT,
    referrer TEXT,
    time_on_page_ms INTEGER,
    viewed_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_tracking_pv_session ON site.tracking_page_views(session_id);
CREATE INDEX idx_tracking_pv_path ON site.tracking_page_views(path);
CREATE INDEX idx_tracking_pv_viewed ON site.tracking_page_views(viewed_at);

-- 4. Tabela de eventos de interacao
CREATE TABLE site.tracking_interaction_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES site.tracking_sessions(id),
    visitor_id UUID NOT NULL REFERENCES site.tracking_visitors(id),
    event_type VARCHAR(50) NOT NULL,
    element_id VARCHAR(255) NOT NULL,
    element_label VARCHAR(255),
    section VARCHAR(100),
    metadata JSONB,
    occurred_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_tracking_ie_session ON site.tracking_interaction_events(session_id);
CREATE INDEX idx_tracking_ie_type ON site.tracking_interaction_events(event_type);
CREATE INDEX idx_tracking_ie_element ON site.tracking_interaction_events(element_id);
CREATE INDEX idx_tracking_ie_section ON site.tracking_interaction_events(section);
CREATE INDEX idx_tracking_ie_occurred ON site.tracking_interaction_events(occurred_at);

-- 5. Tabela de eventos de scroll
CREATE TABLE site.tracking_scroll_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES site.tracking_sessions(id),
    visitor_id UUID NOT NULL REFERENCES site.tracking_visitors(id),
    page_path VARCHAR(500) NOT NULL,
    max_depth INTEGER NOT NULL,
    visible_section VARCHAR(100),
    occurred_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_tracking_se_session ON site.tracking_scroll_events(session_id);
CREATE INDEX idx_tracking_se_depth ON site.tracking_scroll_events(max_depth);
CREATE INDEX idx_tracking_se_occurred ON site.tracking_scroll_events(occurred_at);

-- 6. Tabela de eventos de conversao
CREATE TABLE site.tracking_conversion_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES site.tracking_sessions(id),
    visitor_id UUID NOT NULL REFERENCES site.tracking_visitors(id),
    event_type VARCHAR(50) NOT NULL,
    plan_id VARCHAR(50),
    plan_name VARCHAR(100),
    billing_cycle VARCHAR(20),
    registration_step INTEGER,
    registration_step_name VARCHAR(100),
    last_feature_viewed VARCHAR(255),
    time_to_convert_ms BIGINT,
    sessions_to_convert INTEGER,
    occurred_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_tracking_ce_visitor ON site.tracking_conversion_events(visitor_id);
CREATE INDEX idx_tracking_ce_type ON site.tracking_conversion_events(event_type);
CREATE INDEX idx_tracking_ce_plan ON site.tracking_conversion_events(plan_id);
CREATE INDEX idx_tracking_ce_occurred ON site.tracking_conversion_events(occurred_at);

-- 7. Tabela de eventos de erro
CREATE TABLE site.tracking_error_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES site.tracking_sessions(id),
    visitor_id UUID NOT NULL REFERENCES site.tracking_visitors(id),
    error_type VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    stack TEXT,
    url TEXT,
    status_code INTEGER,
    occurred_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_tracking_ee_type ON site.tracking_error_events(error_type);
CREATE INDEX idx_tracking_ee_occurred ON site.tracking_error_events(occurred_at);

-- 8. Tabela de snapshots de performance
CREATE TABLE site.tracking_performance_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES site.tracking_sessions(id),
    visitor_id UUID NOT NULL REFERENCES site.tracking_visitors(id),
    page_load_time_ms INTEGER,
    fcp_ms INTEGER,
    lcp_ms INTEGER,
    fid_ms INTEGER,
    cls DECIMAL(5,3),
    ttfb_ms INTEGER,
    device_type VARCHAR(20),
    browser VARCHAR(100),
    recorded_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_tracking_ps_session ON site.tracking_performance_snapshots(session_id);
CREATE INDEX idx_tracking_ps_recorded ON site.tracking_performance_snapshots(recorded_at);

-- 9. Tabela de metricas diarias pre-calculadas
CREATE TABLE site.tracking_daily_metrics (
    date DATE NOT NULL,
    metric_name VARCHAR(100) NOT NULL,
    metric_value DECIMAL(15,4) NOT NULL,
    dimensions JSONB,
    PRIMARY KEY (date, metric_name, dimensions)
);

CREATE INDEX idx_tracking_dm_date ON site.tracking_daily_metrics(date);
CREATE INDEX idx_tracking_dm_metric ON site.tracking_daily_metrics(metric_name);
