-- Push Subscriptions (dispositivos)
CREATE TABLE app.push_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    user_role VARCHAR(30) NOT NULL,
    organizacao_id BIGINT NOT NULL,
    endpoint TEXT NOT NULL,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    user_agent TEXT,
    dt_criacao TIMESTAMP DEFAULT now(),
    CONSTRAINT pk_push_subscription PRIMARY KEY (id),
    CONSTRAINT fk_push_sub_organizacao FOREIGN KEY (organizacao_id) REFERENCES app.organizacao(id),
    CONSTRAINT uk_push_sub_endpoint UNIQUE (endpoint)
);

CREATE INDEX idx_push_sub_user ON app.push_subscription(user_id, user_role);
CREATE INDEX idx_push_sub_org ON app.push_subscription(organizacao_id);

-- Notificacoes Push (historico in-app)
CREATE TABLE app.notificacao_push (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    user_role VARCHAR(30) NOT NULL,
    organizacao_id BIGINT NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT,
    origem VARCHAR(100),
    detalhe TEXT,
    prioridade VARCHAR(10) DEFAULT 'MEDIA',
    categoria VARCHAR(30) DEFAULT 'SISTEMA',
    lido BOOLEAN DEFAULT FALSE,
    icone VARCHAR(255),
    url_acao VARCHAR(500),
    is_sw BOOLEAN DEFAULT FALSE,
    dt_cadastro TIMESTAMP DEFAULT now(),
    dt_read TIMESTAMP,
    CONSTRAINT pk_notificacao_push PRIMARY KEY (id),
    CONSTRAINT fk_notif_push_organizacao FOREIGN KEY (organizacao_id) REFERENCES app.organizacao(id)
);

CREATE INDEX idx_notif_push_user ON app.notificacao_push(user_id, user_role, lido);
CREATE INDEX idx_notif_push_org ON app.notificacao_push(organizacao_id);
CREATE INDEX idx_notif_push_dt ON app.notificacao_push(dt_cadastro DESC);
