CREATE TABLE app.api_keys
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    user_type      VARCHAR(20)                             NOT NULL,
    username       VARCHAR(255)                            NOT NULL,
    organizacao_id BIGINT                                  NOT NULL,
    key_hash       VARCHAR(128)                            NOT NULL,
    name           VARCHAR(100)                            NOT NULL,
    description    VARCHAR(500),
    ativo          BOOLEAN                                 NOT NULL,
    last_used_at   TIMESTAMP WITHOUT TIME ZONE,
    expires_at     TIMESTAMP WITHOUT TIME ZONE,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_api_keys PRIMARY KEY (id)
);