-- Codigos de recuperacao de senha
CREATE TABLE app.password_reset_code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    user_role VARCHAR(30) NOT NULL,
    email VARCHAR(255) NOT NULL,
    code VARCHAR(6) NOT NULL,
    reset_token VARCHAR(255),
    code_expires_at TIMESTAMP NOT NULL,
    token_expires_at TIMESTAMP,
    code_used BOOLEAN DEFAULT FALSE,
    token_used BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT now(),
    CONSTRAINT pk_password_reset_code PRIMARY KEY (id)
);

CREATE INDEX idx_prc_user_code ON app.password_reset_code(user_id, user_role, code_used);
CREATE INDEX idx_prc_reset_token ON app.password_reset_code(reset_token) WHERE reset_token IS NOT NULL;
CREATE INDEX idx_prc_code_expires ON app.password_reset_code(code_expires_at);
