CREATE TABLE admin
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizacao_id BIGINT                                  NOT NULL,
    username       VARCHAR(255)                            NOT NULL,
    password       VARCHAR(255)                            NOT NULL,
    email          VARCHAR(255)                            NOT NULL,
    nome_completo  VARCHAR(255)                            NOT NULL,
    ativo          BOOLEAN                                 NOT NULL,
    role           VARCHAR(255),
    dt_criacao     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT pk_admin PRIMARY KEY (id)
);

ALTER TABLE admin
    ADD CONSTRAINT uc_admin_email UNIQUE (email);

ALTER TABLE admin
    ADD CONSTRAINT uc_admin_username UNIQUE (username);

ALTER TABLE admin
    ADD CONSTRAINT FK_ADMIN_ON_ORGANIZACAO FOREIGN KEY (organizacao_id) REFERENCES organizacao (id);
