
CREATE TABLE instance
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    instance_name       VARCHAR(100)                            NOT NULL,
    qrcode              TEXT,
    status              VARCHAR(20)                             NOT NULL,
    phone_number        VARCHAR(20),
    profile_picture_url VARCHAR(500),
    profile_name        VARCHAR(100),
    webhook_url         VARCHAR(500),
    webhook_enabled     BOOLEAN                                 NOT NULL,
    webhook_events      TEXT,
    reject_call         BOOLEAN                                 NOT NULL,
    msg_call            VARCHAR(500),
    groups_ignore       BOOLEAN                                 NOT NULL,
    always_online       BOOLEAN                                 NOT NULL,
    read_messages       BOOLEAN                                 NOT NULL,
    read_status         BOOLEAN                                 NOT NULL,
    organizacao_id      BIGINT                                  NOT NULL,
    is_active           BOOLEAN                                 NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    description         TEXT,
    CONSTRAINT pk_instance PRIMARY KEY (id)
);

ALTER TABLE instance
    ADD CONSTRAINT uc_instance_instancename UNIQUE (instance_name);

ALTER TABLE instance
    ADD CONSTRAINT FK_INSTANCE_ON_ORGANIZACAO FOREIGN KEY (organizacao_id) REFERENCES organizacao (id);


