
CREATE TABLE instance
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    instance_id    VARCHAR(100)                            NOT NULL,
    instance_name  VARCHAR(100)                            NOT NULL,
    integration    VARCHAR(255)                            NOT NULL,
    personality    VARCHAR(255),
    description    TEXT,
    organizacao_id BIGINT                                  NOT NULL,
    tool_id        BIGINT,
    webhook_id     BIGINT,
    CONSTRAINT pk_instance PRIMARY KEY (id)
);

CREATE TABLE instance_tools
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    get_services            BOOLEAN                                 NOT NULL,
    get_professional        BOOLEAN                                 NOT NULL,
    get_products            BOOLEAN                                 NOT NULL,
    get_avaliable_schedules BOOLEAN                                 NOT NULL,
    post_scheduling         BOOLEAN                                 NOT NULL,
    send_text_message       BOOLEAN                                 NOT NULL,
    send_media_message      BOOLEAN                                 NOT NULL,
    post_confirmations      BOOLEAN                                 NOT NULL,
    post_cancellations      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_instance_tools PRIMARY KEY (id)
);

CREATE TABLE instance_webhook
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url       VARCHAR(255)                            NOT NULL,
    token     VARCHAR(255)                            NOT NULL,
    enabled   BOOLEAN                                 NOT NULL,
    by_events BOOLEAN,
    base64    BOOLEAN,
    events    TEXT,
    CONSTRAINT pk_instance_webhook PRIMARY KEY (id)
);

ALTER TABLE instance
    ADD CONSTRAINT uc_instance_instanceid UNIQUE (instance_id);

ALTER TABLE instance
    ADD CONSTRAINT uc_instance_instancename UNIQUE (instance_name);

ALTER TABLE instance
    ADD CONSTRAINT uc_instance_tool UNIQUE (tool_id);

ALTER TABLE instance
    ADD CONSTRAINT uc_instance_webhook UNIQUE (webhook_id);

ALTER TABLE instance
    ADD CONSTRAINT FK_INSTANCE_ON_ORGANIZACAO FOREIGN KEY (organizacao_id) REFERENCES organizacao (id);

ALTER TABLE instance
    ADD CONSTRAINT FK_INSTANCE_ON_TOOL FOREIGN KEY (tool_id) REFERENCES instance_tools (id);

ALTER TABLE instance
    ADD CONSTRAINT FK_INSTANCE_ON_WEBHOOK FOREIGN KEY (webhook_id) REFERENCES instance_webhook (id);

